### ISSUE TITLE
Arrow keys not working properly

### ISSUE THREAD

**Issue by MonteyMontey** [learncodebygaming/pydirectinput#4]
I tried to simulate arrow key presses for a DirectX 11 game but only 'up' is working as expected. 'right', 'left' and 'down' are mapped to different keys or don't work.

**Comment by learncodebygaming** [comment]
I agree this still isn't working as well as it should. I'll work on a fix, but in the meantime you might try toggling your Num Lock key to see if you get better results.

**Comment by learncodebygaming** [comment]
I've released a new build to address this. Please try version 1.0.2.

It addresses the issue of the arrow key scancodes possibly being different on different hardware by using MapVirtualKey to do the scancode lookup from the virtual key code. It uses a different scancode to deal with either NumLock state so that it no longer behaves like the shift key is being held down between arrow presses. Also it will now set the ExtendedKey flag for arrow keys, which I found necessary to get the arrow keys working on Half-Life 2 (and possibly other Direct3D games).

**Comment by MonteyMontey** [comment]
Works fine for me now :thumbsup:
